### ISSUE TITLE
support WebSocket Scope released in Spring 4.1

### ISSUE THREAD

**Issue by xmlking** [zyro23/grails-spring-websocket#10]
Looking for session scope support for storing WebSocket's user session data similar to HTTP session.
Saw `WebSocket Scope` in Spring 4.1 release notes. Hope it is some kind of HTTPSession scope for WebSockets.

**Comment by zyro23** [comment]
2.0.0.M1 working together with grails-3.0.0.m2 has been published to bintray. spring version is 4.1.5 so all the new 4.1 goodies are included/available.
currently not planning to provide a trait to make websocket session/request etc. available as "properties" because the request (message) as well as the session can be resolved as handler method arguments (e.g. via `SimpMessageHeaderAccessor` and/or `StompHeaderAccessor`).
```groovy
@MessageMapping("/foo/bar")
void fooBar(SimpMessageHeaderAccessor smha) {
    def sessionId = smha.sessionId
    def sessionAttrs = smha.sessionAttributes // Map<String, Object>
    ...
}
```
