### ISSUE TITLE
Support for Grails 3.0

### ISSUE THREAD

**Issue by dtamm** [zyro23/grails-spring-websocket#19]
Since Grails 3.0 is the new Master (in Git), i want to try this plugin out with Grails 3.0. A support for Grails 3.0 would be nice!

**Comment by xmlking** [comment]
since Grails 3.0 M1 is out , wonder when new plugin will be ready. looking forword to use session and new @SendToUser

**Comment by zyro23** [comment]
currently sorting out some remaining issues with asset-pipeline for grails-3.0.0.m1. as soon as that is ready ill merge grails3 into master and start to try releasing milestones. leaving this open until then so you get the news asap.

**Comment by xmlking** [comment]
Thanks @zyro23 found this artical about aspect-pipeline in grails 3.0 
http://davydotcom.com/blog/2015-01-29-grails-3-0-0-m1-asset-pipeline-tips-tricks

This is off topic but wonder if you know how `delegate` works in grails 3.0 *Plugin.groovy ?
Keep getting `delegate` undefined....

https://github.com/xmlking/grails3-spring-batch/blob/master/src/main/groovy/grails/plugin/springbatch/SpringBatchGrailsPlugin.groovy#L67

**Comment by zyro23** [comment]
seen the article. currently the main remaining issue is that grails-gradle-plugin puts asets under jar:/assets while aset-pipline expects them under jar:/META-INF/assets. but pr is already pending: https://github.com/grails/grails-core/pull/560

reg your plugin spring closure delegate issue - should work imho. see https://github.com/grails/grails-core/blob/master/grails-spring/src/main/groovy/grails/spring/BeanBuilder.java#L752 ... what error are you getting exactly?

**Comment by xmlking** [comment]
in `build.gradle`  `publishing.publications.maven.artifactId "spring-websocket"` seems not working.
when i run gradle `publishToMavenLocal` command , it produced `grails-spring-websocket-2.0.0.BUILD-SNAPSHOT.jar` not `spring-websocket-2.0.0.BUILD-SNAPSHOT.jar`

**Comment by zyro23** [comment]
hi, you checked `build/libs`, right? if you look under `<home>/.m2/` (the local maven cache), it will be published there as expected (at least thats what i am seeing). to use it in an app just make sure your you got the `mavenLocal()` repository added in `build.gradle`.

however, i am not yet 100% sure if the naming stays this way or if i will publish as `grails-spring-websocket` because of the jar naming conflict with Spring core `spring-websocket-x.y.z.jar`.
if i change sth there, readme will reflect it.

**Comment by xmlking** [comment]
Got it. Thanks.

**Comment by zyro23** [comment]
please note that i decided to do the renaming. using `grails-spring-websocket` as maven artefact id now on grails3 branch. group stays `org.grails.plugins`. will need to figure out how to best publish grails3 plugins anyway (grails central vs. bintray vs. ?).

**Comment by zyro23** [comment]
so looks like finally grails-3.0.0.m2 declares the necessary asset-pipeline dependencies so that binary plugin asset resolution works.
i merged the grails3 branch into master today and released a 2.0.0.M1 to bintray/jcenter.
you are very much welcome to give it a spin.
closing this issue. if you find any problems please do not hesitate to raise a corresponding issue here.

**Comment by xmlking** [comment]
for some reason I have to return some junk to make the page show up, otherwise it shows blank page.
any one else experiencing this issue with Grails 3 and JDK 8?

```groovy
class ExampleController {

    //def index() {}

    def index() {
        [junk: []] //<--- I had to do this. without it I am getting blank page !
    }

    @MessageMapping("/hello")
    @SendTo("/topic/hello")
    protected String hello(String world) {
        return "hello from controller, ${world}!"
    }

}
```

**Comment by zyro23** [comment]
yup had that, too. a `render view: "index"` does the job as well. but has hardly anything to do with spring-websocket support. please use the grails jira if thats worth raising an issue.
thanks, zyro

**Comment by zyro23** [comment]
https://jira.grails.org/browse/GRAILS-12028
https://github.com/grails/grails-core/commit/fe20a2ed5092cbf40426f26ccd25e20b9456c11f
jeff has taken care of it.
