### ISSUE TITLE
Sample using WebSocket please 

### ISSUE THREAD

**Issue by anderskristian** [zyro23/grails-spring-websocket#25]
The sample using SockJS makes the solution very difficult to understand.

SockJS will first use WebSocket - as I understand. Then it will change protocol to other things maybe Comet??

And I find this is NO good for the plugin.
We need to make sure that the WebSocket specification is solved to call the plugin xxx-websocket.
And I cannot make that work (other issue)

**Comment by zyro23** [comment]
the intention of the plugin is to make spring-websocket with its stomp broker and annotation handling available to grails apps.
if you just want to use springs websocket api (i.e. implement a handler) without the sock.js fallback behavior you can always do so without this plugin (http://docs.spring.io/spring/docs/current/spring-framework-reference/html/websocket.html#websocket-server).
i think calling this plugin `spring-websocket` is just fine because
* thats the framework it builds upon/supports and
* if client and server both support websocket communication, websocket is the protocol and transport that will be used. fallback transports are necessary because this is not guaranteed.

**Comment by zyro23** [comment]
works as designed. spring and sockjs docs should have the general fallback transport behavior covered.

**Comment by anderskristian** [comment]
Thanks a lot for your quick answers. 
OK for me to close it..
