### ISSUE TITLE
Can Grails Web profile dependency be removed?

### ISSUE THREAD

**Issue by kastork** [zyro23/grails-spring-websocket#34]
With Grails 3.1 I can imagine apps that want to use sockets without the Grails web profile - rest/API servers with push capability, for example.  Do you think the dependency on web profile here in the plugin can be removed?

**Comment by zyro23** [comment]
yea sure! as minimal as possible i guess. what would the result look like? do you have any example?

maybe sth. like this?

```groovy
dependencies {
	provided "org.grails:grails-dependencies"
	provided "org.grails:grails-web-boot"
	provided "org.springframework.boot:spring-boot-autoconfigure"
	provided "org.springframework.boot:spring-boot-starter-logging"
	provided "org.springframework.boot:spring-boot-starter-actuator"
	provided "org.springframework.boot:spring-boot-starter-tomcat"

	compile "com.fasterxml.jackson.core:jackson-databind:2.6.3"
	compile "org.springframework:spring-messaging:${springVersion}"
	compile "org.springframework:spring-websocket:${springVersion}"
}
```

**Comment by kastork** [comment]
I'm noodling around with plugin development really for the first time.  No pro at it, no example so far.  I figure start with

`grails create plugin grails-spring-websocket --profile=plugin` and then only add what's really necessary.

Does that Tomcat dependency you added have implications for non-tomcat deployments?  The spring package has classes that mention several platforms other than Tomcat.

**Comment by zyro23** [comment]
ok let me try

**Comment by zyro23** [comment]
could you please try 2.3.0.M2 and see if everything is working as expected? i tried to reduce the dependencies to what seems to be a minimum to me:
```
provided "javax.servlet:javax.servlet-api:3.1.0"
provided "org.grails:grails-plugin-async"
```
`grails-plugin-async` depends on `grails-plugin-controllers` and `grails-plugin-events` which seems to be a good fit.
i had to explicitly put in the dependency to `servlet-api` because i could not figure out where grails depends on it in a scope that makes it available to a plugins compile scope... but that should not harm (how would you use websockets in this environment without servlet-api anyways).

**Comment by kastork** [comment]
This looks really promising.  I've got an app made with the rest-api profile connecting and subscribing to a queue.

**Comment by kastork** [comment]
Seems ok.  Grails is moving so fast lately -- hard to keep up.
