### ISSUE TITLE
Unable to receive messages after sending an acknowledgment to external broker

### ISSUE THREAD

**Issue by helgew** [zyro23/grails-spring-websocket#38]
My requirements include the sending of acknowledgements once a message is received. My understanding from the documentation is that this requires an external broker. After installation and configuration of RABITMQ, clients are able to send and receive messages as long as they do not send an acknowledgement. Once an acknowledgement is sent, no further messages are received on either the client or the remote broker.The controller method is being called though when the client tries to send.

To illustrate, I have created a project at https://github.com/helgew/grails-websocket-example .

**Comment by zyro23** [comment]
just sent a pr to your sample that uses a queue instead of a topic.

if you take a look at the rabbitmq console you will see that now an actual named queue is being used instead of the direct topic exchange `amq.topic`.

explicitly {{ack}}ing / {{nack}}ing a message does not really make sense on a topic exchange given its publish/subscribe characteristics anyway, i guess?

hth.

**Comment by zyro23** [comment]
seems to be solved according to slack feedback. root cause was putting `ack: 'client'` into the connection headers instead of the subscription headers of the stomp.js client where it belongs.
