### ISSUE TITLE
Proposal: Startup Performance

### ISSUE THREAD

**Issue by davydotcom** [zyro23/grails-spring-websocket#57]
We have been using this plugin for quite some time and our app contains over 3200 beans on the registry (from various other modules) and 302 controllers. I have been experimenting with replacing the AbstractMethodMessageHandler to have it only grab beans of type controller which has helped but with 302 controllers still takes around 9 seconds to scan. Then I realized something, in Grails Controllers are @Lazy beans. Meaning this plugin is instantiating all of them when it starts up and does a plugin scan, thus affecting startup performance across the board. A proposal would be to define a new Artefact type of `WebSocketController` or something like that that is reserved for websocket message mapping handlers to be used. This would reduce the bean scanning behavior. I can do the work but curious what your thoughts are before hand

**Comment by zyro23** [comment]
nice find! maybe also of interest for @dularion as #49 could be related.

so first let me double check if there is a way to inspect regular grails `Controller` candidates without triggering instantiation/initialization.

there is of course always the option to use spring `@Controller` beans and put the websocket handling methods in there. maybe that approach mitigates the need for a new artefact type?

i thought about a new artefact type ("websocketController", "websocketHandler", etc.) already when creating the plugin but then chose to stick with the same approach as spring does (scanning controllers for message handler methods).

**Comment by dularion** [comment]
Oh cool, this sounds very interesting indeed!

**Comment by davydotcom** [comment]
I think a separate artefact makes more sense and let me go over why. One it limits the scope and provides a "convention" over "configuration" approach in line withe Grails mantra. Also it enables one to add special helper methods on the artefact to make things easier to deal with. For example, we could lazy init the persistenceInterceptor for GORM sessions easily without the user needing to wrap because `withNewSession` is actually not the best way to do it and ensure a clean thread. Also it allows simpler references to things like `convertAndSend` without needing to explicitly type `brokerMessagingTemplate`

**Comment by zyro23** [comment]
so i tried to reproduce the slowdown again. i think this time with success. referenced sample app has 3k beans, 300 spring controllers as well as 300 grails controllers. some di, some scaffolding, controllers having 10 actions each.

and this is what i see:
```
Invoking afterPropertiesSet() on bean with name 'profilingGrailsSimpAnnotationMethodMessageHandler'
afterPropertiesSet() / detectHandlerMethods() took 22.965 s

Invoking afterPropertiesSet() on bean with name 'profilingSpringSimpAnnotationMethodMessageHandler'
afterPropertiesSet() / detectHandlerMethods() took 0.056 s
```
so something is really going on with the handler method scan of grails controllers.

also, you can see in the debug log of the application that the grails controllers are **not** instantiated/initialized during the handler method lookup. instantiation does happens first once a controller is targeted by a web request, as expected.
but still, we see that drastic slowdown. i will try to find out what is going on there with grails controller classes that impacts the scanning performance that much. maybe ast transforms add some kind of heavy overhead there..

anyway, at least in the meantime this also shows that scanning of spring `@Controller` beans is fast. which one possible solution is indeed to:
* use a custom websocket config class as explained in the readme
* remove the `GrailsSimpAnnotationMethodMessageHandler` bean definition from it
* put the message handler methods into `@Controller` annotated beans

@davydotcom i welcome pull-requests of course but i guess whatever support for a new artefact type would look like, we should keep scanning grails controller classes by default in order to prevent a breaking change. tbh i did not add more features to this plugin to keep maintenance at a minimum.

will provide feedback if i find sth.

**Comment by davydotcom** [comment]
Fixed with latest release M1 by using WebSocket artefact and WebSocket message handler
