### ISSUE TITLE
Is there any support for Grails 6.x?

### ISSUE THREAD

**Issue by vsachinv** [zyro23/grails-spring-websocket#72]
@zyro23 Any plan to upgrade the plugin for Grails 6.x?

**Comment by zyro23** [comment]
i just released a `2.6.0-RC1` from branch `2.6.x`: https://github.com/zyro23/grails-spring-websocket/tree/2.6.x

breaking changes:
* the maven group id has changed to `io.github.zyro23` due to changes in the plugin release process
  * maybe that can be mitigated/reverted for a 2.6.0+ final release but for the time being, it is what it is..
* the plugin no longer ships sock.js by default as browser and infra support for websocket connections is standard by now
  * the readme [samples/snippets](https://github.com/zyro23/grails-spring-websocket/tree/2.6.x?tab=readme-ov-file#client-side-stompjs) reflect that
  * if you really need sock.js, it can be added manually at any time
* the plugin now ships [stomp.js](https://github.com/stomp-js/stompjs) `7.0.0`
  * the readme [samples/snippets](https://github.com/zyro23/grails-spring-websocket/tree/2.6.x?tab=readme-ov-file#client-side-stompjs) reflect that as well
  * you are free to use other stomp clients, of course

note that using spring-websocket directly is a viable (and arguably preferred) alternative to this plugin, ref.:
* https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#messaging.websockets
* https://docs.spring.io/spring-framework/reference/web/websocket.html
* https://docs.spring.io/spring-framework/reference/web/websocket/stomp.html

**Comment by gsartori** [comment]
Thank you, we use your plugin to update the UI from connected industrial machines (Serial ports and sockets over RJ45). True, we can use Spring directly, but it's also true that your plugin works just out of the box and it's simple to use.

BTW, would you mind merging the latest release to the "main" branch so visitors can see the plugin is maintained? Actually it looks like it is not.

**Comment by vsachinv** [comment]
@zyro23 Thanks fir the update and support. Will try to use the same

**Comment by zyro23** [comment]
`2.6.x` has been merged into main
